CleanOceanAction/coa_ui

- src/App.js
- src/DateRange.js
- src/DirtyDozen.js
- src/LocationDetails.js
Jerry - I created a master branch so we could easily keep track of changes. Could you please check that these are correct and then merge them in?
> Connect to back-end

- package-lock.json
- package.json
- src/App.js
- src/FilterOptions.js
- src/HeaderNavigation.js
- src/HistoricalTrendsChart.css
- src/HistoricalTrendsChart.js
- src/LocationDetails.js
- src/Routes.js
- src/Site.js
- src/Trends.css
- src/Trends.js
- Implemented routing so that when inter-app links work without refreshing the page. 
- Minor layout fixes to the 'Site' and 'Trends' page.
- Implemented the layout for the 'Trends' page with dummy data for the line chart.
> Routing and minor layout fixes

- src/LocationDetails.js
- src/Site.js
This commit fixes a bug caused by my last commit. 
Certain properties were removed by Jerry in commit where he connects the front end to the backend: 
https://github.com/CleanOceanAction/coa_ui/commit/49eb126bb9d3a397b1214f90a2f47c5e6922cff2#diff-5a090b92f9d2df15e91ef33b06ad8cd3
My commit however reintroduced the removed properties: 
https://github.com/CleanOceanAction/coa_ui/commit/651bb6be5b4d659e03fe5cc37666587ee956fa4a#diff-5a090b92f9d2df15e91ef33b06ad8cd3
> Bug fix - remove previously deleted properties

- src/DateRange.js
- src/DirtyDozen.js
- src/LocationDetails.css
- src/LocationDetails.js
- src/Site.js
incl. some formatting... sorry, haha
> page loads up with valid data

- src/DateRange.js
- src/DirtyDozen.js
- src/LocationDetails.js
Also includes support for different location categories
> valid date ranges support

- README.md
@maithuvenkatesh @jerrylin1218
> Include link to the site

- src/DirtyDozen.js
@jerrylin1218 This actually only requires these two changes as we probably don't want to change the chart as that would look overcrowded. Just changing the table header and contents is needed here.
Fixes #31
> Add material name into the table

- src/LocationDetails.js
Fixes #24
As mentioned in the issue, just needed to make a quick change to the transformation of the drop down to clear it out.
> Clear out dropdown when new area is selected

- src/BackendAccessor.js
- src/components/DataGrid.js
- src/contributions/ContributionForm.js
- src/contributions/events/EventAccessor.js
- src/contributions/events/EventAdd.js
- src/contributions/events/Events.js
- src/contributions/items/ItemAccessor.js
- src/contributions/items/Items.js
- src/contributions/sites/SiteAccessor.js
- src/contributions/sites/Sites.js
Display relevant information on the Sites and Items tabs. This is my current stopping point in case we want to deploy something to Paul and Mike for demoing purposes to show that we've made some progress. There's definitely still a lot more to be done.
Refactor the grid component and utilize it for the sites and items tabs.
> Add sites and items stubs and refactor grid

- src/contributions/event-items/EventItemPopup.js
The required field didn't have a star which others do.
It was added
> Add a star to quantity to imply it is a required field

- src/contributions/events/EventDetails.js
The current trash bag count uses a positive integer input when it can be positive floating points. 
Changed it.
> Change trashbags to floating point

- Makefile
- package-lock.json
- src/contributions/events/Events.css
- src/contributions/events/Events.js
Previously the event selection items were spread out each on its own row.
Brought them together and put them on the same row to save vertical space.
Also ended up making a few generic changes when rebuilding the env.
> Make the selections for event on the same row

- src/contributions/event-items/EventItems.js
- src/contributions/events/Events.js
Adds in updated by and time for events and event items.
> Add the extra two columns for updated by and time

- package-lock.json
- package.json
- src/components/DataGrid.js
Swapped out the Edit and Delete for Icons
As I was adding packages I also saw some dependencies needed updating for security so that is in here too.
> Swap edit and delete for icons

- src/components/DataGrid.js
The add wasn't as noticeable with it saying `New`.
Changed it to be an icon in theme with the edit and delete. To make it more noticeable then just a plus it is a white plus inside a blue square icon.
> Changed add to a plus with a dark square around it

- src/components/DataGrid.js
- src/contributions/event-items/EventItems.js
- src/contributions/events/Events.js
Added a totals summary row for events and event items for relevant values.
> Add totals summary row

- package-lock.json
- package.json
- src/components/SelectCustom.js
- src/contributions/ThreeTierSelect.js
- src/contributions/event-items/EventItemPopup.js
- src/contributions/events/EventPopup.js
- src/contributions/items/ItemPopup.js
- src/contributions/items/ItemSelector.js
- src/contributions/items/Items.js
- src/contributions/sites/SiteSelector.js
Supports the adding and editing of items.
> Support Add and Edit Items

- src/components/FloatInput.js
- src/components/ZipCodeInput.js
- src/contributions/sites/SitePopup.js
- src/contributions/sites/Sites.js
Implements adding and editing the sites popup.
*The Zip code input could be improved quite a bit, but I left it flexible for now.
> Implement add and edit sites

- src/contributions/events/EventDetails.js
- src/contributions/events/EventPopup.js
- src/contributions/events/Events.js
> Swap order of meta data to match their excel sheets

- src/contributions/event-items/EventItems.js
- src/contributions/events/Events.js
- src/contributions/items/Items.js
- src/contributions/sites/Sites.js
When deletion happens and it fails, it would fail silently.
Added popups to warn someone it did not delete, and why this might have happened.
> Add a popup on failing to delete

- package-lock.json
- src/HeaderNavigation.js
- src/Routes.js
The navigation links would open in the same page and mess with the history so when trying to go back it would be finicky.
Had the new links open in a new tab instead.
> Open up navigation links in a new tab

- src/contributions/event-items/EventItems.js
Default event items to sort by update time ascending, so that the screen mimics the COA user's excel sheet.
> Default event items to sort by update time ascending
